version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: install-npm
          command: sudo npm install -g npm@latest
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: build
          command: npm start
